name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Run lint command
        run: npm run lint
  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Run build command
        run: npm run build
      - name: Run test command
        run: npm run test:only
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PRESENCE: ${{ secrets.PRESENCE }}
          PREFIX: ${{ secrets.PREFIX }}
          GUILDID: ${{ secrets.GUILDID }}
          CORDETOKEN: ${{ secrets.CORDETOKEN }}
          CHANNELID: ${{ secrets.CHANNELID }}
          BOTID: ${{ secrets.BOTID }}
          DIDYOUMEAN: true
          DISABLE_WEB: true
          WEB: WEB
          SECRET: SECRET
          LOCALE: en
          
